### ISSUE TITLE
ER図の作成

### ISSUE THREAD

**Issue by Yokovzjhd2** [Yokovzjhd2/Atte#1]

**Comment by Yokovzjhd2** [comment]
![Atte drawio](https://user-images.githubusercontent.com/99689906/173590323-4808f2a0-39a8-48d5-9bc2-d9c2f28a52c0.svg)

**Comment by Yokovzjhd2** [comment]
ER図を作成しました。確認お願いします。

**Comment by gem-yours** [comment]
- working_hoursは勤務開始・終了時間から計算することが出来るので定義しなくても大丈夫です
- 休憩時間についてですが、こちらは開始時間と終了時間を記録しておく必要があります。休憩時間を直接入力するわけではなく休憩開始・終了ボタンを押す方式になっているので、それぞれのボタンを押した時間を保存しておかないと休憩時間が分からなくなってしまいます。
- Start_timesとEnd_timesはまとめて1つのエンティティにした方がコーディングのときに取り回しが良くなります。

**Comment by Yokovzjhd2** [comment]
ありがとうございます。確認しました。
本日中に修正させていただきます。

**Comment by Yokovzjhd2** [comment]
![Atte drawio](https://user-images.githubusercontent.com/99689906/174151510-731ac42d-45b2-4b4e-a925-d68c219e5cbc.svg)

**Comment by Yokovzjhd2** [comment]
修正させていただきました。確認お願いします。

**Comment by Yokovzjhd2** [comment]
![Atte drawio](https://user-images.githubusercontent.com/99689906/174151882-b3f599ac-3152-4ac7-b7ff-dd2d2e635619.svg)

**Comment by gem-yours** [comment]
OKです。次はテーブル定義の記入ですが、こちらは実際にテーブルを作成した後に記入して頂いて大丈夫です。
テーブルの作成はマイグレーションファイルを利用して行うので、まずは #2 のプロジェクトの準備のissueを行っていただき、その後 #3 のマイグレーションファイルの作成を行って頂く流れになります。（ここからはgitでcommitして頂くことになります）
また、こちらの作業は完了いたしましたので画面下の`close issue`ボタンからissueのcloseを行って下さい。
