### ISSUE TITLE
シーディングの作成

### ISSUE THREAD

**Issue by Yokovzjhd2** [Yokovzjhd2/Atte#4]

**Comment by Yokovzjhd2** [comment]
- [ ] workingのデータの編集
- [ ] breakingのデータの編集
- [ ] ６件以上のデータを作成
fakerとfactoryを使用

**Comment by Yokovzjhd2** [comment]
7/8

**Comment by Yokovzjhd2** [comment]
factoryを用いてユーザーのダミーデータを６件作成するということですが、以前作成したシーディングのデータである/seeders/DatabaseSeeder.php内の、
    public function run()
    {
        $param = [
            'name' => '山田　太郎',
            'email' => 'a123@sample.com',
            'password' => 'password'
        ];
        DB::table('users')->insert($param);
    }

を削除して

public function run()
    {
        User::factory()->count(6)->create(); 
    }

を記述するという認識で正しいでしょうか？

**Comment by gem-yours** [comment]
Userのファクトリはデフォルトで用意されているので、上記の記述だけで大丈夫です。

**Comment by Yokovzjhd2** [comment]
ありがとうございます。以下の認識で正しいでしょうか？
1.workingとbreakingのファクトリーファイルをそれぞれ作成
2.それぞれのシーダーファイルを作成
3.２のファイルに６件以上のダミーデータを作る文を記述
4.２のファイルをDatabaseSeederに登録
5.Seederの実行

**Comment by gem-yours** [comment]
その認識でOKです

**Comment by Yokovzjhd2** [comment]
ありがとうございます!
現在上記の４まで終了し、php artisan db:seedを実行しましたがエラーが発生しました。一度自分で考えてみましたが、現状では原因がよくわからなかったので一度今の状態でpushさせて頂きました。確認お願いします。エラー対応は引き続き考えてみますが、もしアドバイス等ありましたらよろしくお願いします。

**Comment by gem-yours** [comment]
pushは成功していますね。ありがとうございます。
`Class 'Databas\Seeders\User' not found`というエラーはクラスが存在していないことを示しています。このエラーが発生する場合は大抵スペルミスかuse文がないときです。
[DatabaseSeederにuse文を追加することでエラーを解消できるはずです。](https://github.com/Yokovzjhd2/Atte/commit/d4f0d803cb6be370ad4ac1b2349e3b7700b84380#diff-ccad8b4ee6013765c2bc672aa0515f8e99e42949c914cce01e0cb2b4e882775d)

**Comment by gem-yours** [comment]
> DatabaseSeederのuseはどのパス名を記述したら良いでしょうか？

すみません、DatabaseSeederで直接ファクトリを呼び出していると勘違いしていました。モデルに対応するシーダファイルをを作成してDatabaseSeederで呼び出す場合はDatabaseSeederにuse文を書く必要はありません。use文が必要なのはModelを使用しているファイル（`モデル名::factory()->count(6)->create();`と記述しているファイル）ですので、それぞれのシーダファイルにuse文を追加して下さい。
また、WowkingとBreakingのモデルが作成されていないのでそちらの作成も必要ですね。

**Comment by Yokovzjhd2** [comment]
ありがとうございます。
シーダーファイル内に
use App\Models\モデル名;
という記述で正しいでしょうか？

**Comment by gem-yours** [comment]
おそらくその記述で動作するはずですが、まだエラーなど出ていますか？
