### ISSUE TITLE
認証機能の作成

### ISSUE THREAD

**Issue by Yokovzjhd2** [Yokovzjhd2/Atte#7]

**Comment by Yokovzjhd2** [comment]
7/14

**Comment by Yokovzjhd2** [comment]
教材を見ながらbreezeのインストール、Node.jsモジュールのインストールとコンパイルまで完了しました。
http://127.0.0.1:8000/registerにアクセスし、認証機能の実装を確認しました。
現在勤怠機能等をまだ作成していない状況ですが、自分のメールアドレスを用いてログインのチェックを行なったりコントローラーの修正は勤怠機能の作成後の方が良いでしょうか？

**Comment by gem-yours** [comment]
> 現在勤怠機能等をまだ作成していない状況ですが、自分のメールアドレスを用いてログインのチェックを行な

ログインのチェックは先にやっておいたほうが良いですね。コントローラの修正はどのような修正を指していますか？
また、ユーザのマイグレーションも一部修正する必要があるので、そちらの対応も勤怠機能の前に行っておいて下さい。

**Comment by gem-yours** [comment]
> ログインは自身のメールアドレスを使用しても大丈夫でしょうか？こういった状況ではテスト用のアドレスを用意するべきでしょうか？

テスト用のアドレスを用意するのが一般的ですね。ただ、今回の場合は個人開発ですのでご自身のメールアドレスを使用しても問題は起きません。

> コントローラの修正

ここに関してはissueのスコープ（＝作業範囲）の問題ですね。ログイン・ログアウトに成功できることまでがスコープの場合はコントローラの修正は必要ありません。実際にユーザがログインしているかチェックできるところまでスコープに含めるのであれば必要です。
もし実際にログインしているかチェックするのであれば、ログイン情報を表示するダミーページを用意し、ログインしていないときにそのページを表示した場合はログイン画面にリダイレクトされるようにする必要があります。（教材のAuthorControlllerの修正が参考になると思います）
自分が認証機能の作成という曖昧な言葉を使ってしまったのがそもそもの問題ではあるのですが、実際の開発でもスコープが曖昧になってしまうことはあります。スコープをどこまでにするのかは早めに認識を合わせられると良いですね。

> ユーザのマイグレーションも一部修正する必要があるので

申し訳ございません、こちらはシーディングと混同しておりました。マイグレーションファイルではなくシーディングファイルの方の修正をお願い致します。
